### ISSUE TITLE
error: unknown option `sort=-taggerdate'

### ISSUE THREAD

**Issue by attack11** [android-linux-stable/script#1]
Hi nathanachance,Nice script! Really thanks for this,Im trying to upstream my kernel, when I run : "./linux-stable.sh -m" I get and error : "error: unknown option `sort=-taggerdate' , And the "Latest kernel version:" its empty, I have the file in the root of my kernel folder

**Comment by nathanchance** [comment]
What is your git version?

**Comment by attack11** [comment]
Hi, Its 1.9.1

**Comment by nathanchance** [comment]
Wow, that's old... The `--sort` option wasn't added until git 2.0.0 ([reference commit](https://github.com/git/git/commit/9ef176b55c373ba087b2d84e77b5713578891927)) and it was updated to use the `for-each-ref` APIs in git 2.7.0 ([reference commit](https://github.com/git/git/commit/b7cc53e92c806b73e14b03f60c17b7c29e52b4a4)). If your distro doesn't have the option to upgrade and you can't find a prebuilt binary somewhere, you can build it yourself.
